"""initial

Revision ID: 9e354d5837e8
Revises: 
Create Date: 2025-06-07 17:16:43.775324

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '9e354d5837e8'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('performance',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('student_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('classe', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('subclasse', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('desempenho', sa.Float(), nullable=False),
    sa.Column('peso_classe', sa.Float(), nullable=False),
    sa.Column('peso_subclasse', sa.Float(), nullable=False),
    sa.Column('peso_por_questao', sa.Float(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('performance', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_performance_student_id'), ['student_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('performance', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_performance_student_id'))

    op.drop_table('performance')
    # ### end Alembic commands ###
